---
version: 2.2
project_name: audiobook-organizer

# Global settings for speed
parallelism: 4
builds_dir: dist

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7
    ldflags:
      - >
        -s -w
        -X audiobook-organizer/cmd.buildVersion={{.Version}}
        -X audiobook-organizer/cmd.buildCommit={{.ShortCommit}}
        -X audiobook-organizer/cmd.buildTime={{.Date}}
    binary: audiobook-organizer

archives:
  - formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else if eq .Arch "arm" }}armv{{ .Arm }}{{- else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*

sboms:
  - id: source-sbom
    artifacts: source
    documents:
      - '{{ .ProjectName }}_{{ .Version }}_source.sbom.cyclonedx.json'
    cmd: syft
    args:
      - .
      - -o
      - cyclonedx-json={{ .Document }}
      - --source-name={{ .ProjectName }}
      - --source-version={{ .Version }}
    env:
      - SYFT_FILE_METADATA_CATALOGER_ENABLED=true
      - SYFT_GO_CATALOGER_ENABLED=true
      - SYFT_PACKAGE_CATALOGER_ENABLED=true

nfpms:
  - package_name: audiobook-organizer
    vendor: jeeftor
    homepage: https://github.com/jeeftor/audiobook-organizer
    maintainer: Jeff Stein <jeffstein@gmail.com>
    description: Audiobook Organizer Tool
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/audiobook-organizer/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/audiobook-organizer/README.md
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

brews:
  - name: audiobook-organizer
    repository:
      owner: jeeftor
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/jeeftor/audiobook-organizer
    description: Audiobook Organizer Tool
    license: MIT
    test: |
      system "#{bin}/audiobook-organizer version -s"
    install: |
      bin.install "audiobook-organizer"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: jeeftor
    name: audiobook-organizer
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release Notes
    For full details, see the [CHANGELOG.md](CHANGELOG.md).
  footer: |
    ## Thanks!
    Thanks to all contributors who helped make this release possible.
  name_template: v{{ .Version }}
