// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {organizer} from '../models';
import {main} from '../models';

export function ExecuteOrganize(arg1:boolean):Promise<organizer.Summary>;

export function GetAvailableLayouts():Promise<Array<main.LayoutOption>>;

export function GetAvailableScanModes():Promise<Array<main.ScanMode>>;

export function GetCurrentFieldMapping():Promise<organizer.FieldMapping>;

export function GetCurrentLayout():Promise<string>;

export function GetCurrentScanMode():Promise<string>;

export function GetFieldMappingOptions():Promise<Array<main.FieldMappingOption>>;

export function GetFieldMappingPresets():Promise<Array<main.FieldMappingPreset>>;

export function GetInitialDirectories():Promise<main.InitialDirectories>;

export function GetLogPath():Promise<string>;

export function GetProgress():Promise<main.ProgressUpdate>;

export function GetSampleMetadataPreviews(arg1:string):Promise<Array<main.MetadataPreview>>;

export function GetSettings():Promise<organizer.OrganizerConfig>;

export function Greet(arg1:string):Promise<string>;

export function PreviewChanges(arg1:string,arg2:string,arg3:Array<number>):Promise<Array<main.PreviewItem>>;

export function ScanDirectory(arg1:string):Promise<Array<organizer.Metadata>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function UpdateFieldMapping(arg1:organizer.FieldMapping):Promise<void>;

export function UpdateFieldMappingField(arg1:string,arg2:string):Promise<void>;

export function UpdateLayout(arg1:string):Promise<void>;

export function UpdateScanMode(arg1:string):Promise<void>;

export function UpdateSettings(arg1:organizer.OrganizerConfig):Promise<void>;
