// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteFileOperations(arg1, arg2) {
  return window['go']['guiapp']['App']['ExecuteFileOperations'](arg1, arg2);
}

export function ExecuteOrganize(arg1) {
  return window['go']['guiapp']['App']['ExecuteOrganize'](arg1);
}

export function GetAvailableLayouts() {
  return window['go']['guiapp']['App']['GetAvailableLayouts']();
}

export function GetAvailableScanModes() {
  return window['go']['guiapp']['App']['GetAvailableScanModes']();
}

export function GetAvailableTemplateFields() {
  return window['go']['guiapp']['App']['GetAvailableTemplateFields']();
}

export function GetBatchPreview(arg1, arg2) {
  return window['go']['guiapp']['App']['GetBatchPreview'](arg1, arg2);
}

export function GetCurrentAuthorFormat() {
  return window['go']['guiapp']['App']['GetCurrentAuthorFormat']();
}

export function GetCurrentFieldMapping() {
  return window['go']['guiapp']['App']['GetCurrentFieldMapping']();
}

export function GetCurrentLayout() {
  return window['go']['guiapp']['App']['GetCurrentLayout']();
}

export function GetCurrentScanMode() {
  return window['go']['guiapp']['App']['GetCurrentScanMode']();
}

export function GetFieldMappingOptions() {
  return window['go']['guiapp']['App']['GetFieldMappingOptions']();
}

export function GetFieldMappingPresets() {
  return window['go']['guiapp']['App']['GetFieldMappingPresets']();
}

export function GetInitialDirectories() {
  return window['go']['guiapp']['App']['GetInitialDirectories']();
}

export function GetLivePreviewPath(arg1, arg2) {
  return window['go']['guiapp']['App']['GetLivePreviewPath'](arg1, arg2);
}

export function GetLogPath() {
  return window['go']['guiapp']['App']['GetLogPath']();
}

export function GetProgress() {
  return window['go']['guiapp']['App']['GetProgress']();
}

export function GetRenameConfig() {
  return window['go']['guiapp']['App']['GetRenameConfig']();
}

export function GetRenamePresets() {
  return window['go']['guiapp']['App']['GetRenamePresets']();
}

export function GetSampleMetadataPreviews(arg1) {
  return window['go']['guiapp']['App']['GetSampleMetadataPreviews'](arg1);
}

export function GetScanStatistics() {
  return window['go']['guiapp']['App']['GetScanStatistics']();
}

export function GetSettings() {
  return window['go']['guiapp']['App']['GetSettings']();
}

export function GetUndoInfo() {
  return window['go']['guiapp']['App']['GetUndoInfo']();
}

export function Greet(arg1) {
  return window['go']['guiapp']['App']['Greet'](arg1);
}

export function LogEvent(arg1) {
  return window['go']['guiapp']['App']['LogEvent'](arg1);
}

export function OrganizeFiles(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['OrganizeFiles'](arg1, arg2, arg3);
}

export function PreviewChanges(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['PreviewChanges'](arg1, arg2, arg3);
}

export function PreviewRename(arg1) {
  return window['go']['guiapp']['App']['PreviewRename'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['guiapp']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['guiapp']['App']['SelectDirectory'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['guiapp']['App']['SetLogLevel'](arg1);
}

export function UndoLastOperation() {
  return window['go']['guiapp']['App']['UndoLastOperation']();
}

export function UpdateAuthorFormat(arg1) {
  return window['go']['guiapp']['App']['UpdateAuthorFormat'](arg1);
}

export function UpdateFieldMapping(arg1) {
  return window['go']['guiapp']['App']['UpdateFieldMapping'](arg1);
}

export function UpdateFieldMappingField(arg1, arg2) {
  return window['go']['guiapp']['App']['UpdateFieldMappingField'](arg1, arg2);
}

export function UpdateLayout(arg1) {
  return window['go']['guiapp']['App']['UpdateLayout'](arg1);
}

export function UpdateRenameConfig(arg1) {
  return window['go']['guiapp']['App']['UpdateRenameConfig'](arg1);
}

export function UpdateScanMode(arg1) {
  return window['go']['guiapp']['App']['UpdateScanMode'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['guiapp']['App']['UpdateSettings'](arg1);
}
