// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {organizer} from '../models';

export function LogEvent(arg1:string):Promise<void>;

export function ExecuteFileOperations(arg1:Array<main.FileOperation>,arg2:boolean):Promise<organizer.Summary>;

export function ExecuteOrganize(arg1:boolean):Promise<organizer.Summary>;

export function GetAvailableLayouts():Promise<Array<main.LayoutOption>>;

export function GetAvailableScanModes():Promise<Array<main.ScanMode>>;

export function GetAvailableTemplateFields():Promise<Array<Record<string, string>>>;

export function GetBatchPreview(arg1:Array<number>,arg2:string):Promise<Array<main.PreviewItem>>;

export function GetCurrentAuthorFormat():Promise<string>;

export function GetCurrentFieldMapping():Promise<organizer.FieldMapping>;

export function GetCurrentLayout():Promise<string>;

export function GetCurrentScanMode():Promise<string>;

export function GetFieldMappingOptions():Promise<Array<main.FieldMappingOption>>;

export function GetFieldMappingPresets():Promise<Array<main.FieldMappingPreset>>;

export function GetInitialDirectories():Promise<main.InitialDirectories>;

export function GetLivePreviewPath(arg1:number,arg2:string):Promise<main.PreviewItem>;

export function GetLogPath():Promise<string>;

export function GetProgress():Promise<main.ProgressUpdate>;

export function GetRenameConfig():Promise<main.RenameConfig>;

export function GetRenamePresets():Promise<Array<Record<string, string>>>;

export function GetSampleMetadataPreviews(arg1:string):Promise<Array<main.MetadataPreview>>;

export function GetScanStatistics():Promise<main.ScanStatistics>;

export function GetSettings():Promise<organizer.OrganizerConfig>;

export function GetUndoInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function OrganizeFiles(arg1:Array<string>,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function PreviewChanges(arg1:string,arg2:string,arg3:Array<number>):Promise<Array<main.PreviewItem>>;

export function PreviewRename(arg1:organizer.Metadata):Promise<string>;

export function ScanDirectory(arg1:string):Promise<Array<organizer.Metadata>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetLogLevel(arg1:string):Promise<void>;

export function UndoLastOperation():Promise<Record<string, any>>;

export function UpdateAuthorFormat(arg1:string):Promise<void>;

export function UpdateFieldMapping(arg1:organizer.FieldMapping):Promise<void>;

export function UpdateFieldMappingField(arg1:string,arg2:string):Promise<void>;

export function UpdateLayout(arg1:string):Promise<void>;

export function UpdateRenameConfig(arg1:main.RenameConfig):Promise<void>;

export function UpdateScanMode(arg1:string):Promise<void>;

export function UpdateSettings(arg1:organizer.OrganizerConfig):Promise<void>;

export function GetCoverArt(arg1:number):Promise<string>;

export function GetValidationWarnings():Promise<Array<main.ValidationWarning>>;
